### ISSUE TITLE
AttributeError: module 'collections' has no attribute 'MutableSequence'

### ISSUE THREAD

**Issue by ernieIzde8ski** [jfcarter2358/jsonc#9]
on void linux, running python 3.10

code:
```python
from pathlib import Path

import jsonc
```
traceback:
```
(venv) [ernie@void-ernie-dt ratbot]$ python setup
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ernie/Projects/ratbot/setup/__main__.py", line 3, in <module>
    import jsonc
  File "/home/ernie/Projects/ratbot/venv/lib/python3.10/site-packages/jsonc/__init__.py", line 183, in <module>
    class JSONCList(collections.MutableSequence):
AttributeError: module 'collections' has no attribute 'MutableSequence'
```

It seems to me the issue is that `collections.MutableSequence` has been moved over to `collections.abc.MutableSequence`, as per [the docs](https://docs.python.org/3/library/collections.abc.html)

**Comment by jfcarter2358** [comment]
Looks like that's exactly the issue, this has been resolved in version 1.0.4 which was just pushed to PyPI.
